//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInventory.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> New { get; set; }
    
        public virtual User User { get; set; }
    }
}
